language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
env:
  - GALLERYDL_TESTS=core
matrix:
  include:
    - python: "3.7"
      dist: xenial
    - python: "3.8-dev"
      dist: xenial
    - python: "3.6"
      env: GALLERYDL_TESTS=results
    - language: minimal
      dist: xenial
      addons:
        snaps:
          - name: snapcraft
            classic: true
      env: SNAP_TESTS=true

git:
  depth: 3
  quiet: true
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+(-\S*)?$/
  - /^test(-\w+)+$/

script:
  - 'if test "${SNAP_TESTS}" != true; then ./scripts/run_tests.sh; else true; fi'
  - 'if test "${SNAP_TESTS}" = true; then sudo apt update && snapcraft --destructive-mode && sudo snap try && snap run gallery-dl --verbose https://twitter.com/ubuntu/status/1121001597092364288; else true; fi'
